version: "3.8"

services:
  absenin-backend:
    image: absenin-backend
    container_name: absenin-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5000"
    env_file:
      - .env.production
